# Generated by Django 4.0.2 on 2022-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Grupo'),
        ),
    ]
