# Generated by Django 4.0.2 on 2022-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipoResidencia',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbano', 'Urbano')], default='Urbano', max_length=7, verbose_name='Tipo da residência'),
        ),
    ]
