# Generated by Django 4.0.2 on 2022-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0002_alter_endereco_tiporesidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='tipoResidencia',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Urbana', 'Urbana')], default='Urbano', max_length=7, verbose_name='Tipo da residência'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, verbose_name='Periodo'),
        ),
    ]
