# Generated by Django 4.0.2 on 2022-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Trabalho', 'Trabalho'), ('Artigo', 'Artigo'), ('Seminário', 'Seminário'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de nota'),
        ),
    ]
