# Generated by Django 4.0.2 on 2022-03-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0003_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
