# Generated by Django 4.0.2 on 2022-03-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0004_alter_endereco_tiporesidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipoAviso', models.CharField(choices=[('Importante', 'Importante'), ('Muito importante', 'Muito importante')], default='Urbana', max_length=50, verbose_name='Tipo do aviso')),
            ],
        ),
    ]
