# Generated by Django 4.0.2 on 2022-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0004_usuario_usename_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
