# Generated by Django 4.0.2 on 2022-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0005_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='aviso',
            field=models.TextField(default=None, verbose_name='Aviso'),
        ),
    ]
