# Generated by Django 4.0.2 on 2022-03-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0009_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usename',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
