# Generated by Django 4.0.2 on 2022-03-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0010_alter_usuario_matricula_alter_usuario_usename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usename',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
