# Generated by Django 4.0.2 on 2022-03-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0011_remove_usuario_usename_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=50, verbose_name='CEP')),
                ('numero', models.PositiveSmallIntegerField(default=0, verbose_name='Numero da residência')),
                ('geolocateRefCod', models.CharField(blank=True, default='', max_length=5, verbose_name='Código da geolocalização')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
