# Generated by Django 4.0.2 on 2022-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades', '0012_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='tipoResidencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rural'), (2, 'Urbano')], default=2, verbose_name='Tipo da residência'),
        ),
    ]
